#!/usr/bin/env python3
"""MCP server: reminder scheduling for HavenCore.

Wraps the autonomy ``/autonomy/items`` REST API so the LLM can create, list,
and cancel one-shot or recurring reminders. The actual delivery at fire time
is handled by ``selene_agent/autonomy/handlers/reminder.py``, which dispatches
to Signal / Home Assistant push / speaker TTS notifiers.

First module on the mcp 2.0 ``MCPServer`` decorator API (the SDK-migration
pilot). The MCP surface is the typed functions registered in
``ReminderToolsServer._build_mcp``: tool names and descriptions come from the
``@mcp.tool(name=..., description=...)`` kwargs, and each ``inputSchema`` is
generated by pydantic from the signature (``Annotated[..., Field(description
=...)]``; optionals are bare-type + ``NULL_OK`` + ``None`` default — see
``modules/_mcp_params.py``). No hand-written ``Tool`` literals, no name
dispatch. The HTTP host (``selene_agent.mcp_http_app``) mounts
``ReminderToolsServer().mcp``; ``main()`` runs the same server over stdio.
"""
import json
import os
from datetime import datetime, timedelta, timezone
from typing import Annotated, Any, Awaitable, Callable, Dict, List, Literal, Tuple
from zoneinfo import ZoneInfo

import aiohttp
from pydantic import Field

from mcp.server import MCPServer

from selene_agent.modules._mcp_params import NULL_OK
from selene_agent.utils.logger import get_logger

logger = get_logger('loki')

AGENT_API_BASE = os.environ.get("AGENT_API_BASE", "http://localhost:6002").rstrip("/")
# Autonomy CRUD lives on the /api-prefixed router (selene_agent.py mounts
# autonomy_router with prefix="/api"), so all endpoints are /api/autonomy/...
AUTONOMY_ITEMS_URL = f"{AGENT_API_BASE}/api/autonomy/items"
LOCAL_TZ_NAME = os.environ.get("CURRENT_TIMEZONE", "UTC") or "UTC"
DEFAULT_CHANNEL = "signal"
ALLOWED_CHANNELS = {"signal", "ha_push", "speaker"}


def _local_tz() -> ZoneInfo:
    try:
        return ZoneInfo(LOCAL_TZ_NAME)
    except Exception:
        return ZoneInfo("UTC")


def _one_shot_cron(fire_at_utc: datetime) -> str:
    """Format a UTC datetime as a single-fire 5-field cron expression in local time."""
    local_dt = fire_at_utc.astimezone(_local_tz())
    return f"{local_dt.minute} {local_dt.hour} {local_dt.day} {local_dt.month} *"


def _parse_iso(value: str) -> datetime:
    if value.endswith("Z"):
        value = value[:-1] + "+00:00"
    dt = datetime.fromisoformat(value)
    if dt.tzinfo is None:
        # Naive ISO timestamps are interpreted in the user's local tz.
        dt = dt.replace(tzinfo=_local_tz())
    return dt.astimezone(timezone.utc)


def _resolve_when(args: Dict[str, Any], *, now_utc: datetime | None = None) -> Tuple[str, bool]:
    """Resolve the time-spec from raw args into ``(cron_expr, one_shot)``.

    Exactly one of ``in_seconds``, ``at``, ``cron`` must be provided.
    """
    if now_utc is None:
        now_utc = datetime.now(timezone.utc)

    keys_set = [k for k in ("in_seconds", "at", "cron") if args.get(k) is not None]
    if len(keys_set) != 1:
        raise ValueError(
            "must specify exactly one of in_seconds / at / cron; got: "
            + (", ".join(keys_set) if keys_set else "none")
        )

    key = keys_set[0]
    if key == "in_seconds":
        secs = int(args["in_seconds"])
        if secs <= 0:
            raise ValueError("in_seconds must be > 0")
        target = now_utc + timedelta(seconds=secs)
        # Cron fires on minute boundaries; round up so the firing is at-or-after the requested moment.
        if target.second or target.microsecond:
            target = target.replace(second=0, microsecond=0) + timedelta(minutes=1)
        return _one_shot_cron(target), True

    if key == "at":
        target = _parse_iso(str(args["at"]))
        if target <= now_utc:
            raise ValueError("`at` must be in the future")
        return _one_shot_cron(target), True

    cron_expr = str(args["cron"]).strip()
    if not cron_expr:
        raise ValueError("`cron` cannot be empty")
    return cron_expr, False


class ReminderToolsServer:
    """Reminder tool surface plus the autonomy-API HTTP calls behind it.

    ``self.mcp`` is the configured ``MCPServer``. The decorated closures in
    ``_build_mcp`` are the MCP surface; they delegate to the dict-shaped
    ``schedule_reminder`` / ``list_reminders`` / ``cancel_reminder`` methods
    (kept dict-shaped so behavior and tests carry over unchanged from the
    hand-dispatch era — ``None`` means "not provided" throughout).
    """

    def __init__(self):
        self.mcp = self._build_mcp()

    def _build_mcp(self) -> MCPServer:
        mcp = MCPServer("havencore-reminder-tools", version="1.0.0")

        # structured_output=False on every tool: results stay a single
        # TextContent JSON string, byte-identical to the pre-MCPServer wire
        # format (no outputSchema in tools/list, no structuredContent).

        @mcp.tool(
            name="schedule_reminder",
            description=(
                "Schedule a reminder for the user. Use for any 'remind me to X' request. "
                "Provide exactly one of `in_seconds` (relative delay; preferred for "
                "phrases like 'in an hour'), `at` (ISO 8601 absolute time, e.g. "
                "'2026-04-27T18:00:00'; naive times are interpreted in local tz), or "
                "`cron` (5-field cron in local tz for recurring; '0 18 * * 0' = "
                "Sundays at 6pm). Default channel is 'signal'. By default the "
                "agent rewrites the reminder body in its own voice at fire time and "
                "may attach a generated image when the channel is 'signal'; pass "
                "`personalize: false` for verbatim delivery."
            ),
            structured_output=False,
        )
        async def schedule_reminder(
            title: Annotated[str, Field(description=(
                "Short reminder text (e.g. 'Take the trash out'). Used as the "
                "notification title and, if `body` is omitted, the body."
            ))],
            body: Annotated[str, NULL_OK, Field(description=(
                "Optional longer body text. Defaults to title."
            ))] = None,
            in_seconds: Annotated[int, NULL_OK, Field(description=(
                "Fire once after this many seconds. Use for 'in N minutes/hours' "
                "style requests."
            ))] = None,
            at: Annotated[str, NULL_OK, Field(description=(
                "Fire once at this absolute time (ISO 8601). Naive timestamps are "
                "interpreted in the user's local timezone."
            ))] = None,
            cron: Annotated[str, NULL_OK, Field(description=(
                "Recurring 5-field cron (minute hour day-of-month month "
                "day-of-week) in local tz. Examples: '0 18 * * 0' = Sundays 6pm; "
                "'30 7 * * 1-5' = weekdays 7:30am."
            ))] = None,
            channel: Annotated[Literal["signal", "ha_push", "speaker"], NULL_OK, Field(description=(
                "Delivery channel. signal = Signal message (default; "
                "cross-location). ha_push = phone push via Home Assistant. "
                "speaker = TTS announcement on a Music Assistant target."
            ))] = None,
            to: Annotated[str, NULL_OK, Field(description=(
                "Optional recipient override per channel: signal phone number, "
                "ha_push notify.<service>, or speaker MA device target."
            ))] = None,
            personalize: Annotated[bool, NULL_OK, Field(description=(
                "Whether the agent rewrites the body in its own voice at fire time "
                "(and may attach a generated image for signal channel). Defaults "
                "to true. Set to false for verbatim delivery."
            ))] = None,
        ) -> str:
            return await self._dispatch("schedule_reminder", self.schedule_reminder, {
                "title": title,
                "body": body,
                "in_seconds": in_seconds,
                "at": at,
                "cron": cron,
                "channel": channel,
                "to": to,
                "personalize": personalize,
            })

        @mcp.tool(
            name="list_reminders",
            description=(
                "List the user's reminders. Returns id, title, next fire time, "
                "cron expression, channel, and one_shot flag. Use this before "
                "cancel_reminder to find the right id."
            ),
            structured_output=False,
        )
        async def list_reminders(
            include_disabled: Annotated[bool, NULL_OK, Field(description=(
                "If true, also include disabled reminders (cancelled or "
                "already-fired one-shots). Default false."
            ))] = None,
        ) -> str:
            return await self._dispatch("list_reminders", self.list_reminders, {
                "include_disabled": include_disabled,
            })

        @mcp.tool(
            name="cancel_reminder",
            description="Cancel a reminder by id. Use list_reminders first to look up the id.",
            structured_output=False,
        )
        async def cancel_reminder(
            id: Annotated[str, Field(description=(
                "The reminder id (UUID), as returned by list_reminders or "
                "schedule_reminder."
            ))],
        ) -> str:
            return await self._dispatch("cancel_reminder", self.cancel_reminder, {"id": id})

        return mcp

    async def _dispatch(
        self,
        name: str,
        impl: Callable[[Dict[str, Any]], Awaitable[Dict[str, Any]]],
        args: Dict[str, Any],
    ) -> str:
        """Run one tool impl with the old call_tool handler's exact contract.

        JSON text out; an unexpected exception becomes a ``{"status":
        "error"}`` payload in ordinary (non-``isError``) content, so the
        agent-visible text stays identical to the hand-dispatch era.
        """
        logger.info(f"Reminder tool called: {name}")
        try:
            result = await impl(args)
        except Exception as e:
            logger.exception(f"reminder tool {name} failed")
            result = {"status": "error", "error": str(e)}
        return json.dumps(result)

    async def schedule_reminder(self, args: Dict[str, Any]) -> Dict[str, Any]:
        title = (args.get("title") or "").strip()
        if not title:
            return {"status": "error", "error": "title is required"}

        body = (args.get("body") or "").strip() or title

        try:
            cron_expr, one_shot = _resolve_when(args)
        except ValueError as e:
            return {"status": "error", "error": str(e)}

        channel = (args.get("channel") or DEFAULT_CHANNEL).strip()
        if channel not in ALLOWED_CHANNELS:
            return {
                "status": "error",
                "error": f"channel must be one of {sorted(ALLOWED_CHANNELS)}; got {channel!r}",
            }

        # personalize defaults to True; only an explicit False opts out.
        personalize = args.get("personalize")
        personalize = True if personalize is None else bool(personalize)

        cfg: Dict[str, Any] = {
            "title": title,
            "body": body,
            "channel": channel,
            "one_shot": one_shot,
            "personalize": personalize,
        }
        to = (args.get("to") or "").strip()
        if to:
            cfg["to"] = to

        payload = {
            "kind": "reminder",
            "name": title[:120],
            "schedule_cron": cron_expr,
            "config": cfg,
            "autonomy_level": "notify",
            "enabled": True,
        }

        try:
            async with aiohttp.ClientSession() as session:
                async with session.post(
                    AUTONOMY_ITEMS_URL,
                    json=payload,
                    timeout=aiohttp.ClientTimeout(total=10),
                ) as resp:
                    text = await resp.text()
                    if resp.status != 200:
                        return {
                            "status": "error",
                            "error": f"autonomy api returned {resp.status}: {text[:300]}",
                        }
                    data = json.loads(text)
        except aiohttp.ClientError as e:
            return {"status": "error", "error": f"autonomy api unreachable: {e}"}

        item = data.get("item") or {}
        return {
            "status": "ok",
            "id": item.get("id"),
            "title": title,
            "channel": channel,
            "cron": cron_expr,
            "one_shot": one_shot,
            "personalize": personalize,
            "next_fire_at": item.get("next_fire_at"),
        }

    async def list_reminders(self, args: Dict[str, Any]) -> Dict[str, Any]:
        include_disabled = bool(args.get("include_disabled"))
        try:
            async with aiohttp.ClientSession() as session:
                async with session.get(
                    AUTONOMY_ITEMS_URL,
                    timeout=aiohttp.ClientTimeout(total=10),
                ) as resp:
                    text = await resp.text()
                    if resp.status != 200:
                        return {
                            "status": "error",
                            "error": f"autonomy api returned {resp.status}: {text[:300]}",
                        }
                    data = json.loads(text)
        except aiohttp.ClientError as e:
            return {"status": "error", "error": f"autonomy api unreachable: {e}"}

        items = data.get("items") or []
        out: List[Dict[str, Any]] = []
        for it in items:
            if it.get("kind") != "reminder":
                continue
            if not include_disabled and not it.get("enabled"):
                continue
            cfg = it.get("config") or {}
            out.append({
                "id": it.get("id"),
                "title": cfg.get("title") or it.get("name"),
                "channel": cfg.get("channel"),
                "one_shot": cfg.get("one_shot", False),
                # Missing personalize on existing rows is treated as True
                # to match the handler's default behavior.
                "personalize": cfg.get("personalize", True),
                "cron": it.get("schedule_cron"),
                "next_fire_at": it.get("next_fire_at"),
                "enabled": it.get("enabled", True),
            })
        return {"status": "ok", "count": len(out), "reminders": out}

    async def cancel_reminder(self, args: Dict[str, Any]) -> Dict[str, Any]:
        item_id = (args.get("id") or "").strip()
        if not item_id:
            return {"status": "error", "error": "id is required"}
        try:
            async with aiohttp.ClientSession() as session:
                async with session.delete(
                    f"{AUTONOMY_ITEMS_URL}/{item_id}",
                    timeout=aiohttp.ClientTimeout(total=10),
                ) as resp:
                    text = await resp.text()
                    if resp.status == 404:
                        return {"status": "error", "error": "reminder not found", "id": item_id}
                    if resp.status != 200:
                        return {
                            "status": "error",
                            "error": f"autonomy api returned {resp.status}: {text[:300]}",
                        }
        except aiohttp.ClientError as e:
            return {"status": "error", "error": f"autonomy api unreachable: {e}"}

        return {"status": "ok", "deleted": True, "id": item_id}


def main():
    """Stdio entry point (``python -m selene_agent.modules.mcp_reminder_tools``)."""
    logger.info("Starting HavenCore Reminder Tools MCP Server (stdio)...")
    ReminderToolsServer().mcp.run("stdio")


if __name__ == "__main__":
    main()
